
HISTAB = 'gdsyxwhistory'
HISQI = 'qishu'
HISTIME = 'time'
HISN1 = 'no1'
HISN2 = 'no2'
HISN3 = 'no3'
HISN4 = 'no4'
HISN5 = 'no5'
HISN6 = 'no6'
HISN7 = 'no7'
HISN8 = 'no8'
HISN9 = 'no9'
HISN10 = 'no10'

TJTAB = 'gdsyxwtongji'
TJQI = 'qishu'
TJRS = 'result'

PSTAB = 'gdsyxwperson'
PSID = 'personID'
PSDEVICE = 'device'
PSSTATUS = 'status'
PSMONEY = 'money'
PSNAME = 'name'
PSHEAD = 'headImage'
PSLEVEL = 'level'

BLTAB = 'gdsyxwbeatlist'
BLID = 'id'
BLQI = 'qishu'
BLTIME = 'time'
BLROAD = 'road'
BLNUMBER = 'number'
BLMONEY = 'money'
BLSTATUS = 'status'
BLPERSON = 'personID'